name: 📺 Auto-generate TV playlists

on:
  schedule:
    - cron: '0 */4 * * *'    # ogni 4 ore
  workflow_dispatch:        # consente il run manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 m3u8 lxml

    - name: Prepara variabili d’ambiente
      run: |
        echo "PZPROXY=${{ secrets.PZPROXY }}"            >> .env
        echo "MFPDD=${{ secrets.MFPDD }}"                >> .env
        echo "PSWMFP=${{ secrets.PSWMFP }}"              >> .env
        echo "RBT_GIT_HTML_BASE_URL=${{ secrets.RBT_GIT_HTML_BASE_URL }}" >> .env
        echo "NOMEGITHUB=${{ secrets.NOMEGITHUB }}"      >> .env
        echo "NOMEREPO=${{ secrets.NOMEREPO }}"          >> .env

    - name: Run all generators
      run: |
        python hat.py
        python thisnot.py
        python fullita.py
        python itapigz.py
        python onlyevents.py
        python sportzone.py
        python skystreaming.py
        python sportstreaming.py
        python calcio.py
        # …aggiungi qui tutti gli altri .py

    - name: Commit & push updated playlists
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🔄 Auto-update playlists"
        file_pattern: "download/*.m3u8"
        branch: "main"
